// Generated by gencpp from file robotclient/GetCoord.msg
// DO NOT EDIT!


#ifndef ROBOTCLIENT_MESSAGE_GETCOORD_H
#define ROBOTCLIENT_MESSAGE_GETCOORD_H

#include <ros/service_traits.h>


#include <robotclient/GetCoordRequest.h>
#include <robotclient/GetCoordResponse.h>


namespace robotclient
{

struct GetCoord
{

typedef GetCoordRequest Request;
typedef GetCoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCoord
} // namespace robotclient


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotclient::GetCoord > {
  static const char* value()
  {
    return "ec7fb4cadb363741bad99758dda47526";
  }

  static const char* value(const ::robotclient::GetCoord&) { return value(); }
};

template<>
struct DataType< ::robotclient::GetCoord > {
  static const char* value()
  {
    return "robotclient/GetCoord";
  }

  static const char* value(const ::robotclient::GetCoord&) { return value(); }
};


// service_traits::MD5Sum< ::robotclient::GetCoordRequest> should match 
// service_traits::MD5Sum< ::robotclient::GetCoord > 
template<>
struct MD5Sum< ::robotclient::GetCoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotclient::GetCoord >::value();
  }
  static const char* value(const ::robotclient::GetCoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotclient::GetCoordRequest> should match 
// service_traits::DataType< ::robotclient::GetCoord > 
template<>
struct DataType< ::robotclient::GetCoordRequest>
{
  static const char* value()
  {
    return DataType< ::robotclient::GetCoord >::value();
  }
  static const char* value(const ::robotclient::GetCoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotclient::GetCoordResponse> should match 
// service_traits::MD5Sum< ::robotclient::GetCoord > 
template<>
struct MD5Sum< ::robotclient::GetCoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotclient::GetCoord >::value();
  }
  static const char* value(const ::robotclient::GetCoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotclient::GetCoordResponse> should match 
// service_traits::DataType< ::robotclient::GetCoord > 
template<>
struct DataType< ::robotclient::GetCoordResponse>
{
  static const char* value()
  {
    return DataType< ::robotclient::GetCoord >::value();
  }
  static const char* value(const ::robotclient::GetCoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTCLIENT_MESSAGE_GETCOORD_H
