// Generated by gencpp from file robotclient/GetCoordRequest.msg
// DO NOT EDIT!


#ifndef ROBOTCLIENT_MESSAGE_GETCOORDREQUEST_H
#define ROBOTCLIENT_MESSAGE_GETCOORDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robotclient
{
template <class ContainerAllocator>
struct GetCoordRequest_
{
  typedef GetCoordRequest_<ContainerAllocator> Type;

  GetCoordRequest_()
    : in(0)  {
    }
  GetCoordRequest_(const ContainerAllocator& _alloc)
    : in(0)  {
  (void)_alloc;
    }



   typedef int8_t _in_type;
  _in_type in;




  typedef boost::shared_ptr< ::robotclient::GetCoordRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robotclient::GetCoordRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCoordRequest_

typedef ::robotclient::GetCoordRequest_<std::allocator<void> > GetCoordRequest;

typedef boost::shared_ptr< ::robotclient::GetCoordRequest > GetCoordRequestPtr;
typedef boost::shared_ptr< ::robotclient::GetCoordRequest const> GetCoordRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robotclient::GetCoordRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robotclient::GetCoordRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robotclient

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robotclient': ['/home/tomek/TheTitans/robot_ws/src/robotclient/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robotclient::GetCoordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robotclient::GetCoordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotclient::GetCoordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robotclient::GetCoordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotclient::GetCoordRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robotclient::GetCoordRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robotclient::GetCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8a5cea836bd62441c9efcd5dff5bc52";
  }

  static const char* value(const ::robotclient::GetCoordRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8a5cea836bd6244ULL;
  static const uint64_t static_value2 = 0x1c9efcd5dff5bc52ULL;
};

template<class ContainerAllocator>
struct DataType< ::robotclient::GetCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robotclient/GetCoordRequest";
  }

  static const char* value(const ::robotclient::GetCoordRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robotclient::GetCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 in\n\
";
  }

  static const char* value(const ::robotclient::GetCoordRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robotclient::GetCoordRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.in);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetCoordRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robotclient::GetCoordRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robotclient::GetCoordRequest_<ContainerAllocator>& v)
  {
    s << indent << "in: ";
    Printer<int8_t>::stream(s, indent + "  ", v.in);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTCLIENT_MESSAGE_GETCOORDREQUEST_H
