// Generated by gencpp from file robotclient/UpdateTwist.msg
// DO NOT EDIT!


#ifndef ROBOTCLIENT_MESSAGE_UPDATETWIST_H
#define ROBOTCLIENT_MESSAGE_UPDATETWIST_H

#include <ros/service_traits.h>


#include <robotclient/UpdateTwistRequest.h>
#include <robotclient/UpdateTwistResponse.h>


namespace robotclient
{

struct UpdateTwist
{

typedef UpdateTwistRequest Request;
typedef UpdateTwistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateTwist
} // namespace robotclient


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotclient::UpdateTwist > {
  static const char* value()
  {
    return "9b8578b5371575f7e032469638abea73";
  }

  static const char* value(const ::robotclient::UpdateTwist&) { return value(); }
};

template<>
struct DataType< ::robotclient::UpdateTwist > {
  static const char* value()
  {
    return "robotclient/UpdateTwist";
  }

  static const char* value(const ::robotclient::UpdateTwist&) { return value(); }
};


// service_traits::MD5Sum< ::robotclient::UpdateTwistRequest> should match 
// service_traits::MD5Sum< ::robotclient::UpdateTwist > 
template<>
struct MD5Sum< ::robotclient::UpdateTwistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotclient::UpdateTwist >::value();
  }
  static const char* value(const ::robotclient::UpdateTwistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotclient::UpdateTwistRequest> should match 
// service_traits::DataType< ::robotclient::UpdateTwist > 
template<>
struct DataType< ::robotclient::UpdateTwistRequest>
{
  static const char* value()
  {
    return DataType< ::robotclient::UpdateTwist >::value();
  }
  static const char* value(const ::robotclient::UpdateTwistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotclient::UpdateTwistResponse> should match 
// service_traits::MD5Sum< ::robotclient::UpdateTwist > 
template<>
struct MD5Sum< ::robotclient::UpdateTwistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotclient::UpdateTwist >::value();
  }
  static const char* value(const ::robotclient::UpdateTwistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotclient::UpdateTwistResponse> should match 
// service_traits::DataType< ::robotclient::UpdateTwist > 
template<>
struct DataType< ::robotclient::UpdateTwistResponse>
{
  static const char* value()
  {
    return DataType< ::robotclient::UpdateTwist >::value();
  }
  static const char* value(const ::robotclient::UpdateTwistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTCLIENT_MESSAGE_UPDATETWIST_H
