// Generated by gencpp from file masterclient/BaseEndGetCoordResponse.msg
// DO NOT EDIT!


#ifndef MASTERCLIENT_MESSAGE_BASEENDGETCOORDRESPONSE_H
#define MASTERCLIENT_MESSAGE_BASEENDGETCOORDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace masterclient
{
template <class ContainerAllocator>
struct BaseEndGetCoordResponse_
{
  typedef BaseEndGetCoordResponse_<ContainerAllocator> Type;

  BaseEndGetCoordResponse_()
    : in(0)  {
    }
  BaseEndGetCoordResponse_(const ContainerAllocator& _alloc)
    : in(0)  {
  (void)_alloc;
    }



   typedef int8_t _in_type;
  _in_type in;




  typedef boost::shared_ptr< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BaseEndGetCoordResponse_

typedef ::masterclient::BaseEndGetCoordResponse_<std::allocator<void> > BaseEndGetCoordResponse;

typedef boost::shared_ptr< ::masterclient::BaseEndGetCoordResponse > BaseEndGetCoordResponsePtr;
typedef boost::shared_ptr< ::masterclient::BaseEndGetCoordResponse const> BaseEndGetCoordResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace masterclient

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'masterclient': ['/home/tomek/TheTitans/robot_ws/src/masterclient/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8a5cea836bd62441c9efcd5dff5bc52";
  }

  static const char* value(const ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8a5cea836bd6244ULL;
  static const uint64_t static_value2 = 0x1c9efcd5dff5bc52ULL;
};

template<class ContainerAllocator>
struct DataType< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "masterclient/BaseEndGetCoordResponse";
  }

  static const char* value(const ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 in\n\
\n\
";
  }

  static const char* value(const ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.in);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BaseEndGetCoordResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::masterclient::BaseEndGetCoordResponse_<ContainerAllocator>& v)
  {
    s << indent << "in: ";
    Printer<int8_t>::stream(s, indent + "  ", v.in);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTERCLIENT_MESSAGE_BASEENDGETCOORDRESPONSE_H
