// Generated by gencpp from file masterclient/BaseEndGetCoord.msg
// DO NOT EDIT!


#ifndef MASTERCLIENT_MESSAGE_BASEENDGETCOORD_H
#define MASTERCLIENT_MESSAGE_BASEENDGETCOORD_H

#include <ros/service_traits.h>


#include <masterclient/BaseEndGetCoordRequest.h>
#include <masterclient/BaseEndGetCoordResponse.h>


namespace masterclient
{

struct BaseEndGetCoord
{

typedef BaseEndGetCoordRequest Request;
typedef BaseEndGetCoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BaseEndGetCoord
} // namespace masterclient


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::masterclient::BaseEndGetCoord > {
  static const char* value()
  {
    return "b6fb5bf1382e6a4ebdbf5eee1e4c5505";
  }

  static const char* value(const ::masterclient::BaseEndGetCoord&) { return value(); }
};

template<>
struct DataType< ::masterclient::BaseEndGetCoord > {
  static const char* value()
  {
    return "masterclient/BaseEndGetCoord";
  }

  static const char* value(const ::masterclient::BaseEndGetCoord&) { return value(); }
};


// service_traits::MD5Sum< ::masterclient::BaseEndGetCoordRequest> should match 
// service_traits::MD5Sum< ::masterclient::BaseEndGetCoord > 
template<>
struct MD5Sum< ::masterclient::BaseEndGetCoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::masterclient::BaseEndGetCoord >::value();
  }
  static const char* value(const ::masterclient::BaseEndGetCoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::masterclient::BaseEndGetCoordRequest> should match 
// service_traits::DataType< ::masterclient::BaseEndGetCoord > 
template<>
struct DataType< ::masterclient::BaseEndGetCoordRequest>
{
  static const char* value()
  {
    return DataType< ::masterclient::BaseEndGetCoord >::value();
  }
  static const char* value(const ::masterclient::BaseEndGetCoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::masterclient::BaseEndGetCoordResponse> should match 
// service_traits::MD5Sum< ::masterclient::BaseEndGetCoord > 
template<>
struct MD5Sum< ::masterclient::BaseEndGetCoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::masterclient::BaseEndGetCoord >::value();
  }
  static const char* value(const ::masterclient::BaseEndGetCoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::masterclient::BaseEndGetCoordResponse> should match 
// service_traits::DataType< ::masterclient::BaseEndGetCoord > 
template<>
struct DataType< ::masterclient::BaseEndGetCoordResponse>
{
  static const char* value()
  {
    return DataType< ::masterclient::BaseEndGetCoord >::value();
  }
  static const char* value(const ::masterclient::BaseEndGetCoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTERCLIENT_MESSAGE_BASEENDGETCOORD_H
