// Generated by gencpp from file masterclient/IteratorResponse.msg
// DO NOT EDIT!


#ifndef MASTERCLIENT_MESSAGE_ITERATORRESPONSE_H
#define MASTERCLIENT_MESSAGE_ITERATORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace masterclient
{
template <class ContainerAllocator>
struct IteratorResponse_
{
  typedef IteratorResponse_<ContainerAllocator> Type;

  IteratorResponse_()
    : ack(0)  {
    }
  IteratorResponse_(const ContainerAllocator& _alloc)
    : ack(0)  {
  (void)_alloc;
    }



   typedef int8_t _ack_type;
  _ack_type ack;




  typedef boost::shared_ptr< ::masterclient::IteratorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::masterclient::IteratorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IteratorResponse_

typedef ::masterclient::IteratorResponse_<std::allocator<void> > IteratorResponse;

typedef boost::shared_ptr< ::masterclient::IteratorResponse > IteratorResponsePtr;
typedef boost::shared_ptr< ::masterclient::IteratorResponse const> IteratorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::masterclient::IteratorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::masterclient::IteratorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace masterclient

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'masterclient': ['/home/tomek/TheTitans/robot_ws/src/masterclient/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::masterclient::IteratorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::masterclient::IteratorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::masterclient::IteratorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::masterclient::IteratorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::masterclient::IteratorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::masterclient::IteratorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::masterclient::IteratorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb706f4edb700568d7fd69c87cdd4a79";
  }

  static const char* value(const ::masterclient::IteratorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb706f4edb700568ULL;
  static const uint64_t static_value2 = 0xd7fd69c87cdd4a79ULL;
};

template<class ContainerAllocator>
struct DataType< ::masterclient::IteratorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "masterclient/IteratorResponse";
  }

  static const char* value(const ::masterclient::IteratorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::masterclient::IteratorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ack\n\
\n\
";
  }

  static const char* value(const ::masterclient::IteratorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::masterclient::IteratorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IteratorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::masterclient::IteratorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::masterclient::IteratorResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTERCLIENT_MESSAGE_ITERATORRESPONSE_H
