// Generated by gencpp from file masterclient/Iterator.msg
// DO NOT EDIT!


#ifndef MASTERCLIENT_MESSAGE_ITERATOR_H
#define MASTERCLIENT_MESSAGE_ITERATOR_H

#include <ros/service_traits.h>


#include <masterclient/IteratorRequest.h>
#include <masterclient/IteratorResponse.h>


namespace masterclient
{

struct Iterator
{

typedef IteratorRequest Request;
typedef IteratorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Iterator
} // namespace masterclient


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::masterclient::Iterator > {
  static const char* value()
  {
    return "8869b2ff5bcea599c212b1e75b68818b";
  }

  static const char* value(const ::masterclient::Iterator&) { return value(); }
};

template<>
struct DataType< ::masterclient::Iterator > {
  static const char* value()
  {
    return "masterclient/Iterator";
  }

  static const char* value(const ::masterclient::Iterator&) { return value(); }
};


// service_traits::MD5Sum< ::masterclient::IteratorRequest> should match 
// service_traits::MD5Sum< ::masterclient::Iterator > 
template<>
struct MD5Sum< ::masterclient::IteratorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::masterclient::Iterator >::value();
  }
  static const char* value(const ::masterclient::IteratorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::masterclient::IteratorRequest> should match 
// service_traits::DataType< ::masterclient::Iterator > 
template<>
struct DataType< ::masterclient::IteratorRequest>
{
  static const char* value()
  {
    return DataType< ::masterclient::Iterator >::value();
  }
  static const char* value(const ::masterclient::IteratorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::masterclient::IteratorResponse> should match 
// service_traits::MD5Sum< ::masterclient::Iterator > 
template<>
struct MD5Sum< ::masterclient::IteratorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::masterclient::Iterator >::value();
  }
  static const char* value(const ::masterclient::IteratorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::masterclient::IteratorResponse> should match 
// service_traits::DataType< ::masterclient::Iterator > 
template<>
struct DataType< ::masterclient::IteratorResponse>
{
  static const char* value()
  {
    return DataType< ::masterclient::Iterator >::value();
  }
  static const char* value(const ::masterclient::IteratorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTERCLIENT_MESSAGE_ITERATOR_H
