// Generated by gencpp from file masterclient/IteratorRequest.msg
// DO NOT EDIT!


#ifndef MASTERCLIENT_MESSAGE_ITERATORREQUEST_H
#define MASTERCLIENT_MESSAGE_ITERATORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace masterclient
{
template <class ContainerAllocator>
struct IteratorRequest_
{
  typedef IteratorRequest_<ContainerAllocator> Type;

  IteratorRequest_()
    : data()  {
    }
  IteratorRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::masterclient::IteratorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::masterclient::IteratorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IteratorRequest_

typedef ::masterclient::IteratorRequest_<std::allocator<void> > IteratorRequest;

typedef boost::shared_ptr< ::masterclient::IteratorRequest > IteratorRequestPtr;
typedef boost::shared_ptr< ::masterclient::IteratorRequest const> IteratorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::masterclient::IteratorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::masterclient::IteratorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace masterclient

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'masterclient': ['/home/tomek/TheTitans/robot_ws/src/masterclient/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::masterclient::IteratorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::masterclient::IteratorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::masterclient::IteratorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::masterclient::IteratorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::masterclient::IteratorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::masterclient::IteratorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::masterclient::IteratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "131c7b16e90d7646b67a1c83cd590279";
  }

  static const char* value(const ::masterclient::IteratorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x131c7b16e90d7646ULL;
  static const uint64_t static_value2 = 0xb67a1c83cd590279ULL;
};

template<class ContainerAllocator>
struct DataType< ::masterclient::IteratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "masterclient/IteratorRequest";
  }

  static const char* value(const ::masterclient::IteratorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::masterclient::IteratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String data\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::masterclient::IteratorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::masterclient::IteratorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IteratorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::masterclient::IteratorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::masterclient::IteratorRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTERCLIENT_MESSAGE_ITERATORREQUEST_H
