(cl:defpackage masterclient-srv
  (:use )
  (:export
   "BASEENDGETCOORD"
   "<BASEENDGETCOORD-REQUEST>"
   "BASEENDGETCOORD-REQUEST"
   "<BASEENDGETCOORD-RESPONSE>"
   "BASEENDGETCOORD-RESPONSE"
   "GETCOORD"
   "<GETCOORD-REQUEST>"
   "GETCOORD-REQUEST"
   "<GETCOORD-RESPONSE>"
   "GETCOORD-RESPONSE"
   "ITERATOR"
   "<ITERATOR-REQUEST>"
   "ITERATOR-REQUEST"
   "<ITERATOR-RESPONSE>"
   "ITERATOR-RESPONSE"
  ))

